{% set name = "hatch-requirements-txt" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_requirements_txt-{{ version }}.tar.gz
  sha256: bb87ecee32e4ac05d09854ac3c279dd526fbd655154acd9cd10c2a4768a83669

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling >=0.21.0
  run:
    - python >=3.6
    - hatchling >=0.21.0
    - packaging >=21.3

test:
  imports:
    - hatch_requirements_txt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/repo-helper/hatch-requirements-txt
  summary: Hatchling plugin to read project dependencies from requirements.txt
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - domdfcoding
    - maresb
