{% set name = "hatch-requirements-txt" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_requirements_txt-{{ version }}.tar.gz
  sha256: 2c686e5758fd05bb55fa7d0c198fdd481f8d3aaa3c693260f5c0d74ce3547d20

build:
  # Technically we should be [py<361] for 0.4.1 but conda doesn't
  # recognise 361 and skips all pythons...
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6.1  # see skip, above
    - pip
    - hatchling
    - wheel
  run:
    - python >=3.6.1  # see skip, above
    - hatchling >=0.21.0
    - packaging >=21.3

# No upstream tests (in GH repo) as we are missing coincidence,
# coverage-pyver-pragma, dist-meta, domdf-python-tools.

test:
  imports:
    - hatch_requirements_txt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/repo-helper/hatch-requirements-txt
  summary: Hatchling plugin to read project dependencies from requirements.txt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  description: |
    This is a plugin for Hatchling that reads the project dependencies from a requirements.txt file.
  dev_url: https://github.com/repo-helper/hatch-requirements-txt
  doc_url: https://github.com/repo-helper/hatch-requirements-txt

extra:
  recipe-maintainers:
    - domdfcoding
    - maresb
