{% set name = "hatch-requirements-txt" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_requirements_txt-{{ version }}.tar.gz
  sha256: bb87ecee32e4ac05d09854ac3c279dd526fbd655154acd9cd10c2a4768a83669

build:
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
    - wheel
  run:
    - python
    - hatchling >=0.21.0
    - packaging >=21.3

test:
  imports:
    - hatch_requirements_txt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/repo-helper/hatch-requirements-txt
  summary: Hatchling plugin to read project dependencies from requirements.txt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  description: |
    This is a plugin for Hatchling that reads the project dependencies from a requirements.txt file.
  dev_url: https://github.com/repo-helper/hatch-requirements-txt
  doc_url: https://github.com/repo-helper/hatch-requirements-txt

extra:
  recipe-maintainers:
    - domdfcoding
    - maresb
